// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migration engine only (runtime clients use the pg adapter with DATABASE_URL).
    // Supabase migrations must use the direct/session connection (5432), not the
    // transaction pooler (6543/pgbouncer), which can't take migration advisory locks.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
